### ISSUE TITLE
Invalid DTD generated for XML document

### ISSUE THREAD

**Issue by orlitzky** [kore/XML-Schema-learner#2]
I finally found a document schema-learn can't handle =)

With 21475901.xml from https://gist.github.com/orlitzky/a03c0c42d2e9d6ed7d76,

``` bash
$ schema-learn 21475901.xml > MLB_Boxscore_XML.dtd
$ xmllint --valid --noout 21475901.xml 
21475901.xml:1: element BFS_Grand_Slams: validity error : Element BFS_Grand_Slams was declared EMPTY this one has content
<BFS_Grand_Slams>0</BFS_Grand_Slams>
...
```

(there are a lot more errors).

**Comment by kore** [comment]
Thanks for your bug report. I can learn a DTD from that XML now and it validates using xmllint.

There were actually two issues:

1) Significant whitespaces were ignored when learning simple types
2) Wrong usage of PHPs empty() function, which considers the string "0" as empty.

**Comment by orlitzky** [comment]
Wonderful, thanks for the quick fix! (What, you don't consider a non-empty string empty??)
